#
# Job pour la restauration de la base mongodb depuis S3 DO
#
apiVersion: batch/v1
kind: Job
metadata:
  name: restore-backup-mongodb
spec:
  template:
    spec:
      restartPolicy: OnFailure  
      containers:
      - name: backup-mongodb-container
        image: vincentfr/s3mongo # Image public
        env:
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb        # Nom du Secret (cf: kubctl get secrets) - crée à l'instal de mongodb avec Helm
              key: mongodb-root-password # La clé (cf: kubctl describle secrets mongodb)
        - name: MONGODB_USER
          value: root
        - name: MONGODB_HOST
          #value: mongodb:27017           # Pour architecture en standalone
          value: mongodb-headless:27017   # Pour architecture en replicaset
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3cmd-secret
              key: access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3cmd-secret
              key: secret_key
        volumeMounts:
        # Montage de la conf S3
        - name: s3cmd-config-volume
          mountPath: /tmp/.s3cfg
          subPath: s3cfg
        # Montage du script via ConfigMap  
        - name: restore-script-volume
          mountPath: /tmp/restore-script.sh
          subPath: restore-script.sh

        command: ["/bin/sh", "-c"]
        args:
        - |
          cp /tmp/.s3cfg /root
          cp /tmp/restore-script.sh /usr/local/bin/
          
          chmod +x /usr/local/bin/restore-script.sh
          
          sed -i "s@ACCESS_KEY_PLACEHOLDER@${AWS_ACCESS_KEY_ID}@" /root/.s3cfg
          sed -i "s@SECRET_KEY_PLACEHOLDER@${AWS_SECRET_ACCESS_KEY}@" /root/.s3cfg              
          echo "Lancement du script /usr/local/bin/restore-script.sh ..."
          /usr/local/bin/restore-script.sh latest

        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
      volumes:
      - name: s3cmd-config-volume
        configMap:
          name: s3cmd-config                
      - name: restore-script-volume
        configMap:
          name: restore-script              